### PR TITLE
build(k8s): add cron data cache

### PR DESCRIPTION
**Pull request by douglasduteil**

### CODE REVIEW

**Comment by lionelB** [comment]
@douglasduteil can you rebase your pr, please ?

**Comment by douglasduteil** [comment]
:up: @lionelB

**Comment by douglasduteil** [comment]
:up: @lionelB 

~300s on first run (https://gitlab.factory.social.gouv.fr/SocialGouv/cdtn-admin/-/jobs/677846)  
~3s afterwards (https://gitlab.factory.social.gouv.fr/SocialGouv/cdtn-admin/-/jobs/677872)

**Comment by lionelB** [comment]
cool but 2 things, the first huge run is because incremental update are made from a n old version so we compute probably 1 month of diff

**Comment by lionelB** [comment]
and of course... thanks @douglasduteil !

**Pull request merged**
