### PR TITLE
ci: run restore container files only for branch pipelines

### PR DESCRIPTION
**Pull request by lionelB**

### CODE REVIEW

**Comment by douglasduteil** [comment]
why no other ?

**Comment by douglasduteil** [comment]
We are missing `$PRODUCTION` no ?

**Comment by lionelB** [comment]
can you detail in which case there is a variable `$PRODUCTION` I didn't think we use it

**Comment by revolunet** [comment]
i think we restrict the job to the review branches here which is intended

**Review by revolunet — APPROVED** [review]

**Pull request merged**
